import Head from "next/head";
import Button from "@mui/material/Button";
import * as React from "react";

const axios = require("axios").default;

const handleOneClickWP = () => {
  axios({
    method: "get",
    url: "https://httpbin.org/ip",
    data: {
      domainName: "Fred",
      sthElse: "Flintstone",
    },
  })
    .then((res) => {
      console.log(res);
    })
    .catch((err) => {
      console.log(err);
    });
};

export default function OneClickWP() {
  return (
    <div>
      <Head>
        <title>One Click WordPress</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <body>
        <div>
          <Button variant="contained" onClick={handleOneClickWP}>
            Create WordPress VS
          </Button>
        </div>
      </body>
    </div>
  );
}
