import Head from "next/head";
import Button from "@mui/material/Button";
import * as React from "react";


export default function OneClickWP() {
  return (
    <div>
      <Head>
        <title>One Click WordPress</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <body>
        <div>
          <Button variant="contained">Create WordPress VS</Button>
        </div>
      </body>
    </div>
  );
}
