export const config = {
  OFS_API_URL: process.env.NEXT_PUBLIC_OFS_API,
  CONNECTED_CALLBACK_URL: process.env.NEXT_PUBLIC_CONNECTED_CALLBACK_URL,
  NEXT_PUBLIC_APP_ID: process.env.NEXT_PUBLIC_APP_ID,
  NEXT_PUBLIC_SECRET: process.env.NEXT_PUBLIC_SECRET,
};
